name_dict = {
    "Ascaris lumbricoides": "蛔虫/似蚓蛔线虫",
    "Trichuris trichiura": "鞭虫/毛首鞭形线虫",
    "Ancylostoma duodenale": "十二指肠钩虫 (钩虫病: Ancylostomiasis)",
    "Necator americanus": "美州板口线虫 (hookworm)",
    "Enterobius vermicularis": "蛲虫/蠕形住肠线虫 (pinworm)",
    "Trichinella spiralis": "旋毛虫/旋毛形线虫",
    "Angiostrongylus cantonensis": "广州管圆线虫",
    "Wuchereria bancrofti": "班氏丝虫 (Filaria)",
    "Brugia malayi": "马来丝虫",
    "Onchocerca volvulus": "盘尾丝线虫",
    "Clonorchis sinensis": "华支睾吸虫/肝吸虫",
    "Fasciolopsis buski": "布氏姜片吸虫/肠吸虫",
    "Paragonimus westermani": "卫氏并殖吸虫/肺吸虫",
    "Schistosoma japonicum": "日本血吸虫 (血吸虫=裂体吸虫)",
    "Taenia solium": "猪带绦虫 (tapeworm)",
    "Taenia saginata": "牛带绦虫 (tapeworm)",
    "Echinococcus granulosus": "细粒棘球绦虫",
    "Echinococcus multilocularis": "多房棘球绦虫",
    "Spirometra mansoni": "曼氏迭宫绦虫",
    "Hymenolepis nana": "微小膜壳绦虫",
    "Diphyllobothrium latum": "阔节裂头绦虫/鱼绦虫",
    "Entamoeba histolytica": "溶组织内阿米巴",
    # "Naegleria fowleri": "福氏耐格里阿米巴",
    # "Acanthamoeba spp": "棘阿米巴属",
    "Giardia lamblia": "蓝氏贾第鞭毛虫",
    "Trichomonas vaginalis": "阴道毛滴虫",
    "Cryptosporidium. Sp.": "隐孢子虫",
    "Leishmania donovani": "杜氏利士曼原虫",
    "Toxoplasma gondii": "刚地弓形虫",
    "Plasmodium vivax": "间日疟",
    "Plasmodium falciparum": "恶性疟"
}
